CREATE TABLE customers (
    cust_id SERIAL PRIMARY KEY,
    cust_name VARCHAR(30) NOT NULL
);

INSERT INTO customers (cust_name)
VALUES ('Raju'), ('Shinchan'), ('Alex'), ('Raj');

CREATE TABLE orders (
    ord_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1),
    ord_date DATE DEFAULT CURRENT_DATE,
    cust_id INT,
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
);

INSERT INTO orders (ord_date, cust_id)
VALUES ('2026-01-03', 1), ('2026-01-04', 2), ('2026-01-22', 1), (CURRENT_DATE, 4);

CREATE TABLE products (
    pro_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1001 INCREMENT BY 1),
    pro_name VARCHAR(40) NOT NULL,
    pro_price NUMERIC(10,2) NOT NULL
);

INSERT INTO products (pro_name, pro_price)
VALUES ('Laptop', 50000), ('Mouse', 200), ('Cable', 399.59), ('Keyboard', 999);

CREATE TABLE order_items (
    item_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10001 INCREMENT BY 1),
    ord_id INT NOT NULL,
    pro_id INT NOT NULL,
    quantity INT NOT NULL,
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
    ON DELETE CASCADE,
    FOREIGN KEY (pro_id) REFERENCES products(pro_id)
    ON DELETE CASCADE
);

INSERT INTO order_items (ord_id, pro_id, quantity)
VALUES (101, 1001, 2), (102, 1002, 4), (101, 1004, 1), (104, 1003, 2);

SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM products;
SELECT * FROM order_items;

-- Question:
-- Display cust_name, pro_name, ord_date, pro_price, quantity, total.
SELECT cust_name, pro_name, ord_date, pro_price, quantity, (quantity * pro_price) AS "Total"
FROM customers
JOIN orders ON orders.cust_id = customers.cust_id
JOIN order_items ON order_items.ord_id = orders.ord_id
JOIN products ON products.pro_id = order_items.pro_id;

--OR

SELECT cust_name, pro_name, ord_date, pro_price, quantity, (quantity * pro_price) AS Total
FROM order_items
JOIN products ON order_items.pro_id = products.pro_id
JOIN orders ON order_items.ord_id = orders.ord_id
JOIN customers ON orders.cust_id = customers.cust_id;
